name: Build

on:
  # masterへのPRマージをトリガーとしてワークフローを開始する
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # 手動実行デバッグ用
  workflow_dispatch: {}

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodules
        id: update
        run: git submodule update --remote --recursive 
      
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneOSX
          unityVersion: 2022.3.1f1
          buildMethod: BuildPipeline.MacOsBuildFromGithubAction
