name: Build

on:
  # masterへのPRマージをトリガーとしてワークフローを開始する
  pull_request:
    branches:
      - master
    types: [closed]

  # 手動実行デバッグ用
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.platform.runner }}
    
    strategy:
      matrix:
        platform:
          - name: StandaloneWindows64
            buildMethod: BuildPipeline.WindowsBuildFromGithubAction
            runner: ubuntu-latest
          - name: StandaloneOSX
            buildMethod: BuildPipeline.MacOsBuildFromGithubAction
            runner: macos-latest
          - name: StandaloneLinux64
            buildMethod: BuildPipeline.LinuxBuildFromGithubAction
            runner: ubuntu-latest
    
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: Assets/Script/Server/moorestech
      # Submoduleの設定
      - name: Init submodules
        id: init
        run: git submodule update --init
      - name: Run git status
        id: status
        run: echo "::set-output name=status::$(git status -s)"

      # 年月日を取得　キャッシュのkeyに利用
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m')" >> $GITHUB_ENV
      
      # キャッシュ keyを月跨ぎで更新することで定期的にキャッシュ自体の更新を行う
      - uses: actions/cache@v3
        with:
          path: Library
          key: "Library_${{ env.CURRENT_DATETIME }}"
      
      # Build
      - name: ${{ matrix.platform.name }} Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.1f1
          buildMethod: ${{ matrix.platform.buildMethod }}
          allowDirtyBuild: true
      
      # TODO mac、Linux版はパーミッションの設定を行う
      # mac版パーミッション設定参考 https://zenn.dev/flamers/articles/fa9a921f08679d#tl%3Bdr

      # Upload Build for Windows, Mac
      - name: ${{ matrix.platform.name }} Upload
        if: matrix.platform.name != 'StandaloneLinux64'
        uses: actions/upload-artifact@v3
        with:
          name: Output_${{ matrix.platform.name }}
          path: Output_${{ matrix.platform.name }}
      
      # Archive and Upload for Linux
      - name: Archive and Upload for Linux
        if: matrix.platform.name == 'StandaloneLinux64'
        run: |
          tar -czvf output.tar.gz Output_${{ matrix.platform.name }}
        uses: actions/upload-artifact@v3
        with:
          name: Output_${{ matrix.platform.name }}
          path: ./output.tar.gz
